<?php
// phpcs:disable Generic.Files.LineLength.TooLong

if (!$block->getEnabled()) {
    return;
}

$selector = 'alo-content-' . uniqid();
$testimonials = $block->getTestimonials();
if (!count($testimonials)) {
    return;
}
?>
<div class="<?= $escaper->escapeHtml($selector) ?>">
    <div class="block-testimonial">
        <?php if ($block->getTitle()): ?>
            <h2 class="block-title title item section-title">
                <span><?= $escaper->escapeHtml($block->getTitle()) ?></span>
            </h2>
        <?php endif; ?>
    </div>
    <div class="block-content">
        <div class="testimonial slider center-mode grid-slider"
            <?php foreach ($block->getFrontendCfg() as $opt): ?>
                data-<?= $escaper->escapeHtml($opt) ?>='<?= $escaper->escapeHtml($block->getData($opt)) ?>'
            <?php endforeach; ?>
            data-center-mode="false"
            data-center-padding="0"
            data-slides-to-show="1"
            data-slides-to-scroll="1"
            data-autoplay="false"
            data-autoplay-speed="3000"
        >
            <?php foreach ($testimonials as $testimonial): ?>
                <div class="item">
                    <div class="inner-customer">
                        <div class="testimonial-author-info">
                            <div class="customer">
                            <div class="testimonial_customer_name">
                                <?= $escaper->escapeHtml($testimonial->getName()); ?>
                            </div>
                            <div class="testimonial-review-summary short">
                                <div class="rating-summary">
                                    <span class="label"><span><?= $escaper->escapeHtml(__('Rating')) ?>:</span></span>
                                    <div class="rating-result"
                                    title="<?= $escaper->escapeHtml(ceil($testimonial->getRatingSummary() * 20)) ?>%">
                                    <span
                                    style="width:<?= $escaper->escapeHtml(ceil($testimonial->getRatingSummary() * 20)) ?>%">
                                        <span>
                                            <?= $escaper->escapeHtml(ceil($testimonial->getRatingSummary() * 20)) ?>%
                                        </span>
                                    </span>
                                    </div>
                                    <div class="tagline">
                                        <?= $escaper->escapeHtml(__('Trusted by Millions of customers'))?>
                                    </div>
                                    <div class="rating-count">
                                       <?= $escaper->escapeHtml($testimonial->getRatingSummary().'.00') ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="testimonial-text">
                            <div class="testimonial-caption center-mode">
                                <?= $escaper->escapeHtml($testimonial->getText()); ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="slider-arrow-container"></div>
        <div class="slider-dot-container"></div>
        <div class="slider-scrollbar">
            <div class="scrollbar-thumb"></div>
        </div>
    </div>
</div>
