<div class="contact-more-info">
    <div class="box">
        <div class="icon-img">
            <img src="<?= $block->getViewFileUrl('images/icon-img-04.png'); ?>" alt="icon-img">
        </div>
        <div class="icon-img">
            <img src="<?= $block->getViewFileUrl('images/icon-img-03.png'); ?>" alt="icon-img">
        </div>
        <div class="icon-img">
            <img src="<?= $block->getViewFileUrl('images/icon-img-02.png'); ?>" alt="icon-img">
        </div>
        <div class="icon-img">
            <img src="<?= $block->getViewFileUrl('images/icon-img-01.png'); ?>" alt="icon-img">
        </div>
    </div>
</div>