<div class="contact-more-info">
    <div class="icon-img">
        <a href="https://www.instagram.com/sillove925?igsh=MWZsZWRjeThrYm13YQ==" target="_blank">
            <img src="<?= $block->getViewFileUrl('images/contact-instagram.png'); ?>" alt="icon-img">
        </a>
    </div>
    <div class="icon-img">
        <a href="https://www.facebook.com/share/1GrR1sbi4x/" target="_blank">
            <img src="<?= $block->getViewFileUrl('images/contact-fb.png'); ?>" alt="icon-img">
        </a>
    </div>
    <div class="icon-img">
        <a href="https://wa.me/9898100925" target="_blank">
            <img src="<?= $block->getViewFileUrl('images/contact-whatsapp.png'); ?>" alt="icon-img">
        </a>
    </div>
</div>