<div class="contact-more-info">
    <div class="icon-img">
        <a href="#">
            <img src="<?= $block->getViewFileUrl('images/contact-instagram.png'); ?>" alt="icon-img">
        </a>
    </div>
    <div class="icon-img">
        <a href="#">
            <img src="<?= $block->getViewFileUrl('images/contact-fb.png'); ?>" alt="icon-img">
        </a>
    </div>
    <div class="icon-img">
        <a href="#">
            <img src="<?= $block->getViewFileUrl('images/contact-whatsapp.png'); ?>" alt="icon-img">
        </a>
    </div>
</div>